AllCops:
  RunRailsCops: true
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'

Style/HashSyntax:
  EnforcedStyle: ruby18

Metrics/LineLength:
  Max: 120
